---
#-------------------------------
# General Site Settings
title: Neil
logo: logo-new.png # You can add own logo.
description: Blog

#-------------------------------
# Author Settings
author:
  name: Neil Chuang
  image: 01.jpg
  say-hello: Hello, Iâ€™m <strong>Neil Chuang</strong>
  bio: Software design, writes about <strong>web</strong> and <strong>personal growth</strong>. I share software tutorials, free resources and inspiration. Loves <a href="#">music</a>.

#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
linkedin: https://bit.ly/3fPlopm # Add your Linkedin handle
github: https://github.com/tsunglinneil # Add your Github handle
instagram: https://www.instagram.com/neil__chuang/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: neil # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: neil__chuang # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
